### ISSUE TITLE
windows github workflow in-tree-build isn't fetching correct SPIRV-Headers commit

### ISSUE THREAD

**Issue by wenju-he** [KhronosGroup/SPIRV-LLVM-Translator#2284]
See https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902076?pr=2281 as example:
linux release build is checking out 1c6bb27:
```
Run actions/checkout@v3
  with:
    repository: KhronosGroup/SPIRV-Headers
    ref: 1c6bb[2](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:2)74[3](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:3)599e6eb6f37b2969acc0aef812e32e3
    path: llvm-project/llvm/projects/SPIRV-Headers
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    lfs: false
    submodules: false
    set-safe-directory: true
  env:
    LLVM_VERSION: 18
    spirv_headers_tag: 1c6bb27[4](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:4)3[5](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:5)99e[6](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:6)eb6f3[7](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:7)b2969acc0aef[8](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:8)[12](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902271?pr=2281#step:6:12)e32e3
```
windows release build is checking main branch and spirv_headers_tag env isn't set.
```
Run actions/checkout@v[3](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902076?pr=2281#step:5:3)
  with:
    repository: KhronosGroup/SPIRV-Headers
    path: llvm-project\\llvm\\projects\\SPIRV-Headers
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    lfs: false
    submodules: false
    set-safe-directory: true
  env:
    LLVM_VERSION: 1[8](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/7294663560/job/19879902076?pr=2281#step:5:8)
```
This issue is causing windows in-tree build fail on llvm_release_140 branch, see https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2280
